### ISSUE TITLE
Unable to install under windows

### ISSUE THREAD

**Issue by kajusK** [SkypLabs/python4yahdlc#3]
Hi,
I'm trying to use this library under windows machine, unfortunately installation using pip fails with:
`
ValueError: path '/home/travis/build/SkypLabs/python4yahdlc/lib/fcs16.c' cannot be absolute
`

When I tried to build the library manually (python3 setup.py install) I've noticed the source files (from lib and include directories) contain only path to correct location. It looks like git submodule init didn't create links to correct locations from these files.

**Comment by SkypLabs** [comment]
Hi @kajusK,

Thank you for your valuable feedback.

I will investigate and come back to you as soon as I get a chance.

**Comment by mmurty** [comment]
@SkypLabs Is this feature implemented? I am trying to compile it on windows but it fails with same errors for me. I am unable to install it using both the ways pip and sources.

**Comment by SkypLabs** [comment]
Hi @mmurty,

Unfortunately, I haven't had a chance to look at it yet. I'm completely swamped with work these days. I will try to fix it very soon.

Thank you for your patience.

**Comment by dkeekstra** [comment]
I looked a little into it and i think it has to do with the recent change of the yahdcl library that now supports CRC32 and by that renamed the file from fcs16 to fcs

**Comment by AlexPantyukhin13** [comment]
Actually, there is problem with symbolic link to submodule. I just copied files from submodule dir to lib and include dir respectively. Currently it builds.

**Comment by Adam-r-grant** [comment]
I managed to get this running on windows by installing with setup.py and changing the source directories. Check the pull request #4  https://github.com/SkypLabs/python4yahdlc/pull/4

change setup.py

``yahdlc = Extension(
    'yahdlc',
    sources = [
        DIR + '/src/python4yahdlc.c',
        DIR + '/yahdlc/c/fcs16.c',
        DIR + '/yahdlc/c/yahdlc.c'
    ],
    include_dirs = [
        DIR + '/yahdlc/c'
    ],
)``

**Comment by SkypLabs** [comment]
Hi all,

The issue is now fixed and Windows has been added to the build matrix to detect potential future regressions. The patch will  be available on PyPI with the next release that I intend to publish as soon as possible.

Thanks @hebenon for your PR but I wanted to rework the way python4yahdlc was packaged to make use of a `pyproject.toml` file (see #5) and so get rid of `setup.py`.
